apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aks-app-chart.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aks-app-chart.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMapData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
