{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "aks-app-chart.externalSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aks-app-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ include "aks-app-chart.secretStoreName" . }}
    kind: SecretStore
  # target:
  #   name: {{ include "aks-app-chart.externalSecretName" . }}
  #   creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
  {{- end }}
{{- end }}
