{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "aks-app-chart.secretStoreName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aks-app-chart.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      {{- with .Values.externalSecrets.secretStore.provider.azurekv.identityId }}
      identityId: {{ . | quote }}
      {{- end }}
      vaultUrl: {{ .Values.externalSecrets.secretStore.provider.azurekv.vaultUrl | quote }}
{{- end }}
